version: 1
keys:
  - &admin_key age12lhj5rwp25uxpp5dkaa6z998m7mmwcg7dequc46a68x46zdza4sqa7uezf
  - &core1_key age1262ecjgugtm72dcdzxzk5gdeays4rxnedqrv280lvkfpwz5q5pnqdgc3ar
  - &core2_key age1au4hsdvem84xgzf7tr2ckpwx2us4hnrkdy2ty45fc9q2exk8rfkq4x46jl
  - &core3_key age1rhfxwge48gwa7nw9ca434slcp2neallqjfwas6vstd2sm674nvwqkj8tw2
  - &core4_key age177ejdf73ajf7grjhd5m8ksalqldlpwg46lfek79nzkaael9k7v5ssfaj2q
creation_rules:
  # Encrypt the dedicated tailscale secret file (only data/stringData fields)
  - path_regex: kubernetes/infrastructure/tailscale/secret\.yaml$
    encrypted_regex: ^(data|stringData)$
    pgp: ""
    key_groups:
      - age:
          - *admin_key
          - *core1_key
          - *core2_key
          - *core3_key
          - *core4_key

  # Specific rule for the k3s agent node token
  - path_regex: ^secrets/k3s-agent-node-token$
    pgp: ""
    key_groups:
      - age:
          - *admin_key
          - *core1_key
          - *core2_key
          - *core3_key
          - *core4_key
