---
apiVersion: v1
kind: Namespace
metadata:
  name: applications
  labels:
    name: applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    name: infrastructure
