apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: applications
  labels:
    app: hello-app
spec:
  replicas: 2 # Start with 2 replicas
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: chadrussell/hello-app:latest
          ports:
            - containerPort: 8080
