apiVersion: v1
kind: Service
metadata:
  name: hello-app-tailscale
  namespace: infrastructure
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: hello-app
  # Cross-namespace selector to select app in applications namespace
  # Note: This requires configuration of NetworkPolicy for cross-namespace traffic
  # or use of ExternalName service type to point to the service in applications namespace
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  # We don't need a specific service type for Tailscale
  type: ClusterIP
