apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: infrastructure
type: Opaque
stringData:
  # You'll need to replace this with your actual Tailscale auth key
  TS_AUTH_KEY: "tskey-auth-REPLACE_WITH_ACTUAL_KEY"
